site_name: Sbekucraft 2.0
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.expand
nav:
  - 'index.md'
  - 'regole.md'
  - 'guida.md'
  - 'modlist.md'
  - client:
    - 'client/client-index.md'