site_name: Sbekucraft 2.0
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.expand
nav:
  - 'index.md'
  - 'regole.md'
  - 'guida.md'
  - 'modlist.md'
  - 'client/index.md':
    - 'client/installazione.md'
    - 'client/guida.md'
    - 'client/modlist.md'
