site_name: Sbekucraft 2.0
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.expand
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - 'index.md'
  - 'regole.md'
  - 'guida.md'
  - 'content.md'
  - 'changelog.md'
  - 'Client':
    - 'client/installazione.md'
    - 'client/guida.md'
    - 'client/content.md'
